version: '3'

services:
  monoservice:
    image: monoservice
    command: npm start 
    restart: always
    networks:
      - traefik-public
    
    environment:
      - AWS_XRAY_DAEMON_ADDRESS=
      - DB_URL=
      - DB_NAME=
      - DB_USER=
      - DB_PWD=
      - DB_HOST=null
      - DB_PORT=null
      - API_HOST=localhost
      - API_PORT=3000
      - NODE_ENV=production
      - JWT_SECRET_USER=123
      - JWT_SECRET_MOTORIST=
      - JWT_SECRET_RESET_PASSWORD=
      - CIELO_MERCHANTKEY=
      - CIELO_MERCHANTID=
      - CIELO_SANDBOX=true
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.bfbackend.entrypoints=web"
        - "traefik.http.services.bfbackend-service.loadbalancer.server.port=3000"
        - "traefik.http.routers.authservice-path.rule=PathPrefix(`/`)"


networks:
  traefik-public:
    external: true

      
